### ISSUE TITLE
web: Better controlled behavior in search components

### ISSUE THREAD

**Issue by bietkul** [appbaseio/reactivesearch#1021]
**Issue Type:**

**Platform:**

**Description:**

**Screenshots:**

**Minimal reproduction of the problem with instructions:**

**Reactivesearch version:** x.y.z

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**
When user sets `onChange`, `onBlur`, `onKeyPress` or any synthetic event on DataSearch/Category Search, we return a callback function with `event`, `tiggerQuery` (which will actually call elasticsearch). When using controlled components it is the responsibility of user/developer to call `tiggerQuery` after event of his choice. This will also allow user to modify value before search, lets say, user wants to replace `and` with logical `&` so that smart elasticsearch query can be executed.
example  

```
<DataSearch
   onChange={(event, triggerQuery) => {
     // in case he wants the similar behaviour as of now 
     // he can call triggerQuery with each change
     // else if he wants to trigger query only on press of enter key
     // he can achieve it in following manner
     if (event.keyCode === 23) { 
       triggerQuery(event.target.value)
     }
  })
 onBlur={(event, triggerQuery) => {
   ....
 })
/>```

**Comment by jyash97** [comment]
I tried to debug the current controlled behavior. So it works fine when there are no URLParams but when we have URLParams. For eg: `?search="da"` and when we reload the page and clear filters it doesn't clear search because of `Datasearch` internal state  `currentValue` which is set to `da`. If this edge case is solved I think we are good with the current controlled Component. Right? @lakhansamani 

You can check the example over here: https://codesandbox.io/s/datasearch-uttzg

**Comment by lakhansamani** [comment]
@jyash97 this is the different edge that should be fixed, you can report this as a separate bug.

**Comment by bietkul** [comment]
@jyash97 There seems to be some bug, I'll fix it in the next release.
