### ISSUE TITLE
[Feature Request] Modify placeholder in dropdown

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#1149]
**Affected Projects**
React

**Is your feature request related to a problem? Please describe.**
Can't change the placeholder in the search of a MultiDropdownList and Dropdown itself.

**Describe the solution you'd like**
https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/shared/Dropdown.js#L185 add a prop here

**Comment by bietkul** [comment]
The current implementation of `placeholder` prop in dropdown components is not correct, it sets the dropdown value but the documentation says that it'll set the placeholder of the search box which should be the ideal case.
We can not change this behavior because it'll break the things for the current users.
@ShahAnuj2610 We need to do these changes.
1. Update the docs of `placeholder` prop, it'll be only applicable when no value is selected.
2. Define a new prop named `searchPlaceholder` by which one can customize the search box placeholder.

**Comment by kud** [comment]
For the moment I did this:

```
            <MultiDropdownList
              placeholder="Cibles"
              componentId="targets"
              dataField="target.type"
```

but yeah, it only changes the placeholder for the select, not the search. `searchPlaceholder` could be the solution!
