### ISSUE TITLE
Preference field on requests

### ISSUE THREAD

**Issue by julillosamaral** [appbaseio/reactivesearch#1216]
Hi,

This is more an informative question rather than an issue.

In the search requests, I see this payload:
```
{"preference":"SearchResult"}
{"query":{"match_all":{}},"size":10,"_source":{"includes":["*"],"excludes":[]},"from":0}
```

Why is the preference sent to the elasticsearch service? Is it really needed?
Is there a way to avoid having that?

Thanks,
Julio

**Comment by siddharthlatest** [comment]
@julillosamaral The `preference` is used by ES to preserve ordering when the same search query is used over. Read more over [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-preference).

**Comment by elektracodes** [comment]
@siddharthlatest I know I am hijacking this unrelated issue but could someone from your team see this issue? https://github.com/appbaseio/reactivesearch/issues/1215
I expected bugs would have been higher on your priority list, since it seems that you look at the issues people write.

**Comment by julillosamaral** [comment]
Thanks @siddharthlatest 
I read that before but didn't understand why it is send always and is not something optional...

I'll close the issue.

**Comment by vadymhimself** [comment]
This results in 400 errors on my instance. 

`{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15},"status":400}`

**Comment by siddharthlatest** [comment]
@vadymhimself Can you create a new issue? Please include more details (a reproducible demo or the entire network request) for us to tell more.

**Comment by vadymhimself** [comment]
@siddharthlatest it unfolded into a what seems to be an ES issue opendistro-for-elasticsearch/security-kibana-plugin#734.
I could use your help with working it around https://github.com/appbaseio/reactivesearch/discussions/1633

**Comment by harrycreator** [comment]
> This results in 400 errors on my instance.
> 
> `{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15},"status":400}`

I receive the same error when try to send the query through a proxy on nodejs backend

**Comment by lorenzocestaro** [comment]
Hello, 
I thought to comment here instead of creating a new issue. I would like to dig deeper to why the preference value is tied to `componentId` values.

I am not an elasticsearch expert, but my understanding is that by setting a `preference` we are forcing the query to be, quoting ES docs, _routed to the same shards in the same order_, every single time. Couldn't this have performance implications? Using simple static strings as `componentId`s the queries from **all** the users of the application will be routed to the same shards. Which means that the load will not be distributed across the whole cluster and some shards will have considerably more load than others.

Can you clarify if this is the case?

**Comment by siddharthlatest** [comment]
@lorenzocestaro Yes, the preference implies the preferred order of search execution is to use the same shards order. Since several search caching in ES works at the shard level, setting this ensures optimal use of caching.

What you're suggesting wrt load distribution is right, it would be more ideal to do this accounting for userId as well as the componentId instead of just the componentId, which is currently the case.

**Comment by lorenzocestaro** [comment]
@siddharthlatest thank you for the quick response. I think this might worth mentioning in the docs, so that users can design the application to pass some user/session identifier to all componentId. Since you confirmed my worries, I am now finding myself in a position where I have to refactor several components to access auth state to get some user identifier. It would be also very nice if an identifier could be specified as a prop to `ReactiveBase` and the library would take care of appending this value to all component ids internally.

**Comment by siddharthlatest** [comment]
@lorenzocestaro This should likely be something we can do at the lib level, changing this at the user end can be cumbersome. Can you file a new issue for this? We will take this up fairly soon given the importance.

**Comment by lorenzocestaro** [comment]
Definitely! I'll open a new issue soon, thank you very much 👍
