### ISSUE TITLE
setSearchParams is not called when filters are cleared

### ISSUE THREAD

**Issue by zvictor** [appbaseio/reactivesearch#1390]
**Affected Projects**
React

**Library Version:** x.y.z
`"@appbaseio/reactivesearch": "3.5.0"`

**Describe the bug**
Given a project with the ReactiveBase's `setSearchParams` prop defined, `setSearchParams` is always called when a filter is selected, as expected.

However, **when individually clearing filters through `SelectedFilters`**, `setSearchParams` is not called and therefore the URL is not updated. The behaviour is different for the "Clear All" button that works as expected

**To Reproduce**
```js
const Page = () => (
    <ReactiveBase {...settings} setSearchParams={()=>alert('success!')}>
        <SelectedFilters onClear={() => alert('setSearchParams should be called now!')} />
        <SingleList
            componentId="BookSensor"
            dataField="original_series.raw"
            size={100}
        />
    </ReactiveBase>
)
```

**Expected behavior**
`setSearchParams` should be called when any single filter is cleared

**Comment by ShahAnuj2610** [comment]
Seems to work for me. Check this: https://codesandbox.io/s/exciting-lederberg-yq3sq?file=/src/index.js. Can you share a reproducible example?

**Comment by carlopascual** [comment]
It's not working on that reproducible for me either..

Expected Behavior: 

1. type anything and press enter (`setSearchParams` should be called.)
2. remove the `BookSensor` filter (`setSearchParams` should be called again, since the active filters have changed; SelectedFilters' `onClear` should be called as well.)

Actual Behavior:

1. type anything and press enter (`setSearchParams` is called.)
2. remove the `BookSensor` filter (only SelectedFilters' `onClear` is called. `setSearchParams` is not called again.)

**Comment by bietkul** [comment]
@carlopascual You have to update the URL as per current values.
The correct way to use `setSearchParams` should be:
```js
setSearchParams={(url) => {
      console.log("url", url);
      window.history.pushState({ path: url }, "", url);
}}
```
Check this [demo](https://codesandbox.io/s/jovial-worker-z9sdh?file=/src/index.js:339-460)
