### ISSUE TITLE
Legacy context API has been detected within a strict-mode tree

### ISSUE THREAD

**Issue by alex09j22** [appbaseio/reactivesearch#1419]
When I use <ReactiveBase> in React v.16.13, I am getting this issue.

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Styled(Component), ThemeProvider
```

How can I solve?

**Comment by jyash97** [comment]
Hey @imfsdev Thanks for reporting the issue. 

To give some context about this warning: This is happening because of Emotion, we have to update it to the latest version and these warnings should be fixed.

You can track this issue over here: https://github.com/appbaseio/reactivesearch/issues/1210

Closing this issue for now as we already have an open issue.
