### ISSUE TITLE
DynamicRangeSlider is not created from v1.4.1-Vue upwards

### ISSUE THREAD

**Issue by hansendx** [appbaseio/reactivesearch#1501]
**Affected Projects**
Vue.JS

**Library Version:** >= v.1.4.1

**Describe the bug**

DynamicRangeSlider component is not added to the HTML, that is rendered in the browser.
There seem to be no error messages in the console, the slider is just non-existent.

**To Reproduce**

Open the example project from the documentation for the DynamicRangeSlider and set the reactivesearch-vue version to v1.4.1 or higher:

https://codesandbox.io/s/green-wave-su0bm

**Expected behavior**

DynamicRangeSlider should be displayed as it was before version v1.4.1.
https://codesandbox.io/s/elegant-christian-c5s9j

**Desktop (please complete the following information):**
 - OS: Ubuntu, Windows 10
 - Browser Chrome, Firefox
 - Version 81.0.4044.138, 76.0

**Comment by hansendx** [comment]
DynamicRangeSlider is still not working in 1.7.6 https://codesandbox.io/s/shy-moon-rftl2

**Comment by gpassarelli** [comment]
@hansendx do you guys have any updates regarding this issue?

**Comment by hansendx** [comment]
@gpassarelli as a user, all I can say is that it still does not work in the newest reractivesearch-vue.
I looked through the changes a while ago but I'm not proficient enough with Vue to identify the problem.  
I have it pinned to 1.2.0 since it is the last version where all functionality we need still works.

**Comment by indykoning** [comment]
It seems to have broken during the update to 1.4.1 
https://github.com/appbaseio/reactivesearch/compare/v1.4.0-vue...v1.4.1-vue

The slider is not showing because the range is null, it seems like range does not get filled dynamically.
https://github.com/appbaseio/reactivesearch/blob/next/packages/vue/src/components/range/DynamicRangeSlider.jsx#L275
Moreover setting this to a range using vue devtools shows the slider, however after filtering or updating it in some other way once again forces it to be null.

**Comment by royduin** [comment]
Thanks @bietkul 💯

**Comment by hansendx** [comment]
Thank you @bietkul :+1:
