### ISSUE TITLE
Custom render method provides incorrect or duplicate data

### ISSUE THREAD

**Issue by edwinsiebel** [appbaseio/reactivesearch#1551]
**Affected Projects**
Only tested in React.

**Library Version:**
3.12.6

**Describe the bug**
When using a custom `render` method in `ReactiveList`, this method seems to be executed multiple times, even though there is only one result to show.
Also the `data` which is injected into the `render` method, seems to be duplicate or even triplicate.

**To Reproduce**
1. Go to: [Sandbox](https://codesandbox.io/s/prod-sunset-sd9ey?file=/src/index.js)
2. Clear the console
3. Select a timestamp (result should only show 1 result) from the facet

   > Multiple entries (including none related) will be logged in the console. 
4. Clear the console
5. Select another timestamp (result should again only show 1 result) from the facet

   > Multiple entries (including none related) will be logged in the console. 

**Expected behavior**
When selecting a facet with one result, only one result should be injected in the `render` method. Or more general: only the appropriate results should be injected into the `render` method.

**Screenshots**
[Sandbox](https://codesandbox.io/s/prod-sunset-sd9ey?file=/src/index.js:680-692) should be enough.

**Desktop (please complete the following information):**
 - OS: Ubunut/Mac
 - Browser Chrome (Chromium), Firefox
 - Version 76, 81

**Comment by bietkul** [comment]
@edwinsiebel There are performance issues with the `ReactiveList` that is triggering the re-rendering.
Check this comment to know how can you optimize it by using a HOC component with `shouldComponentUpadte` https://github.com/appbaseio/reactivesearch/issues/1086#issuecomment-537052319. There are no duplicate results, the data you see is the older data and it'll get replaced by fresh data when search request is completed. We have those performance issues on our list and a fix will be out soon.
Closing it because an open issue is already present on this topic at here #1086
You can keep the discussion going on there.
