### ISSUE TITLE
Discussion - Point in time API

### ISSUE THREAD

**Issue by ghost** [appbaseio/reactivesearch#1557]
**Affected Projects**
All

**Describe the solution you'd like**
Support for point in time API. - https://www.elastic.co/guide/en/elasticsearch/reference/7.10/point-in-time-api.html
The new point in time API (elastic 7.10) states that there is some performance benefit for fetching hits - potentially performance deficit for fetching aggregations.

I wonder what your thoughts are on whether this is beneficial for the library to support - why/ why not?

**Comment by siddharthlatest** [comment]
The main benefit cited is a better consistency for consecutive search requests, which may otherwise not be consistent due to refreshes having happened in between. There is no performance benefit besides this that the doc points to. Also, this is an X-Pack only feature at this point.

For the time being, I don't see the value of adding support for pit. Also, this is always possible for a user to add with either `defaultQuery` or `customQuery`.
