### ISSUE TITLE
Dynamic Slider no way to handle error

### ISSUE THREAD

**Issue by sunnyunde-xooa** [appbaseio/reactivesearch#2015]
**Affected Projects**
React

**Library Version:** 3.34.3

**Describe the bug**
When using the Dynamic Range Slider as component for search filter. If no data is present in the index or provided with incorrect field, it goes in infinite loop. Due to no way to handle the error on the component not able to do control the error.

**To Reproduce**
Code sanbox link: [https://codesandbox.io/s/clever-glitter-wco6kt?file=/src/index.js](https://codesandbox.io/s/clever-glitter-wco6kt?file=/src/index.js)
Add a Dynamic Slider component with incorrect field or create a index with no data.
Disable enableAppbase

**Expected behavior**
If no data is present or field provided is incorrect a proper error to be thrown and way to handle error in this component.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser [Chrome, Firefox]
 - Version [latest]

**Additional context**
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**NOTE**: If this issue is fixed please share the link to the solution.
Thank You.

**Comment by ubaranzorlu** [comment]
I have been trying to dodge this for a long time. I think it is because my elastic search returns aggregation buckets as follows which is null instead of numerical values

```json
"aggregations": {
    "min": {
        "value": null
    },
    "max": {
        "value": null
    }
}
```

<img width="578" alt="image" src="https://user-images.githubusercontent.com/12199040/184704801-3ad76505-5690-4088-b33d-b4be3a37c973.png">

and I got this as a bonus

<img width="741" alt="image" src="https://user-images.githubusercontent.com/12199040/184705015-0e2199e7-fd1e-451c-8a6e-3b8b0b42c5bd.png">

**Comment by ubaranzorlu** [comment]
I have solved this error by putting [my fork of appbaseio-apps/reactivesearch-proxy-server](https://github.com/ubaranzorlu/reactivesearch-proxy-server) in between elastic server and the reactivesearch. There I have a response middleware where I replace null min with 0 and null max with a float *2.147483647* so that I can catch it later on the front-end and handle the situation by disabling this filter.

**Comment by sunnyunde-xooa** [comment]
Yes, Handling it with help of middleware solved the issue.
Thanks @ubaranzorlu.
