### ISSUE TITLE
app/appName is too oriented appbaseio products

### ISSUE THREAD

**Issue by kud** [appbaseio/reactivesearch#207]
**Issue Type:**
enhancement

**Description:**
You use the value/prop `app` or `appName` in your code or doc but it's clearly too oriented to your company projects.

I had tough time to understand what it is, and it should be called `indices` like it's called in ES doc. https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

Thank you.

**Comment by metagrover** [comment]
Good point, thanks for the feedback. 

We have built this library also keeping in mind, the developers who are not so familiar with Elasticsearch ecosystem, and since the library is fully compatible with appbase.io where we don't expose the concept of `indices`, it made sense for us to use `app` or `appName` as the prop name. We will update our docs to cover this surely.

Although, it's a good point, having `indices` as the prop-name improves the experience for developers familiar with Elasticsearch.

Thoughts @siddharthlatest?

**Comment by kud** [comment]
No worries, I understand. ;) It's just I took time to understand what means `appName` in our own ES. :)

**Comment by divyanshu013** [comment]
Added in docs https://github.com/appbaseio/reactive-manual/commit/3e45504037875f4eaec7cde979346877429f97fb

Thanks @kud 👍

**Comment by kud** [comment]
Haaaa amazing! Thank you @divyanshu013 !
