### ISSUE TITLE
ReactiveComponent URLParams has no effect if using CustomQuery and not setQuery

### ISSUE THREAD

**Issue by rgb-panda** [appbaseio/reactivesearch#2185]
**Affected Projects**
React 

**Library Version:** x.y.z
3.43.7

**Describe the bug**

I'm using ReactiveComponent with customQuery and URLParams={true}, and it's working well in terms of the query and search but the URLParams are never updated.

I looked into the examples in the documentation and saw that there is a prop called setQuery that could be used. I tried it and that fixes the URLParams issue.

Is that an expected behavior that custom query doesn't support URLParams or is that a bug that needs to be resolved?

**Comment by rgb-panda** [comment]
Another issue that would prevent me from using setQuery is that it doesnt support highlight

**Comment by rgb-panda** [comment]
Hello @SavvyShah any comments regarding this issue?

Thanks

**Comment by SavvyShah** [comment]
Can you please explain the use case here? I'm not sure how you want to use the customQuery or what you are trying to achieve.

I've made a [codesandbox here](https://codesandbox.io/s/smoosh-haze-wwhx2i?file=/src/index.js). Although I have defined a customQuery it still updates the URLParams.

**Comment by rgb-panda** [comment]
Thanks @SavvyShah yes I can see this works, but we still need to have CustomComponent and use setQuery. Is that expected? If custom query already has the query, why do I need the setQuery?

If I just have a ReactiveComponent like below shouldn't it still work? For me, it works but doesn't reflect in URLParams

`
<ReactiveComponent
                        URLParams=true
                        componentId={componentId}
                        filterLabel={label}
                        render={() => (
                            ... 
                        )}
                        customQuery={() => {
                            query
                        }}
>
`

**Comment by SavvyShah** [comment]
Yes. You're right. Generally, you don't have to use both of them in your use-case.

URLParams are updated by the library internally. For non-custom components it's value is determined by the value of the filter which is managed by the library. Since in a custom component(filter created using ReactiveComponent), we own the value of filter, we render the options and determine how user interacts with them. Hence, we call `setQuery` passing the value of the filter.

If you want to change query dynamically using the custom component you created you should use `setQuery` provided as props in the component which would sync with the URLParams. 

However if you want to update the dependent component without user interacting with your component, like selecting a value, then you should use `customQuery`. Here there is no way for the library to know the value of filter unless you explicitly set. One use case is mentioned in [the documentation](https://docs.reactivesearch.io/docs/reactivesearch/react/advanced/reactivecomponent/#usage-with-customquery).

**Comment by rgb-panda** [comment]
Thanks @SavvyShah your suggestion worked for us but unfortunately it's ignoring the highlight. Is there any way to do it with highlight?

setQuery(
 { query: {
            bool: {
                should: getShouldMatch(isExactMatch, selectedSearch),
                minimum_should_match: 1,
            },
        },
        highlight: {
            fields: getHighlightedFields(isExactMatch),
            number_of_fragments: 0,
        },
        value: selectedSearch,
}
);
