### ISSUE TITLE
ReactiveBase always does http auth (even if there are no credentials)

### ISSUE THREAD

**Issue by a-n-d-i** [appbaseio/reactivesearch#241]
Hi,

thanks for the awesome framework!

I have an issue with the http-basic auth for non-localhost connections. If I do something like the following for anything but localhost, it generates an basic auth request, leading to a 403.

<ReactiveBase
  app="appname"
</ReactiveBase>

Since we're developing in a private virtual cloud with an open elasticsearch instance it is kind of annoying to run everything through a proxy. It would be nice to be able to disable http-auth or to put a big fat warning in the documentation concerning the behavior because it is sort of counter-intuitive.

Cheers and thanks for your good work, Andi

**Comment by metagrover** [comment]
Hi @a-n-d-i, thanks for bringing this up!

We had actually fixed the core issue earlier, but somehow we skipped to update it in the container component. So now, if you use `url` prop in `ReactiveBase` component, the auth headers will only be sent if the `credentials` prop is set.

Fixed the issue here: 678e233 and it will be out in the next release shortly.

**Comment by a-n-d-i** [comment]
@metagrover: Thanks for the fast reaction, we really appreciate it!

**Comment by metagrover** [comment]
Released in `v2.2.1` 🎉
