### ISSUE TITLE
Update List Components Interactively

### ISSUE THREAD

**Issue by yytsui** [appbaseio/reactivesearch#411]
**Issue Type:enhancement**

**Platform:**

**Description:**

If there are  many list components, when a user click one option, how to make other options
in the same list component or other list component also get updated interactively?

For example , in this [searchkit demo](http://demo.searchkit.co/), after a user choose one of the option
in "Actors", not only the search result update, but also all the navigation components(numbers in Writers, Categories, IMDB rating...) on the left sidebar also get updated!

But in this [reactivesearch ecommerce demo](https://opensource.appbase.io/reactivesearch/demos/ecommerce/), after a user choose one of the option in "Vehicle Type", only the search results update, all the navigation components(numbers in Car, Rating, Price Range) stay the same. Is there any way to modify this demo to  make the the navigation components also get updated interactively such as the searchkit demo mentioned above?

This issue maybe relate to #281.

Thanks!

**Comment by metagrover** [comment]
It's pretty trivial. You just need to use the `react` prop of these components set properly to watch for the changes on desired components.

If we have `A`, `B` and `C` components, and I want `C` to respond to the changes on `A` and `B`, `react` prop of `C` should look like:

```
react={{
   and: ['A', 'B'],
}}
```

or, any other desired relationship combination with `and`, `or` and `not`. [You can learn all about the react prop here](https://opensource.appbase.io/reactive-manual/advanced/react.html).

--------------

@divyanshu013 Can you please update the examples to have proper `react` prop set, so that the components are dependent on each other? This should be applicable to gihub-search-app, ecommerce-app, and goodbooks-app.

**Comment by yytsui** [comment]
Thanks, I made a patch to try the "react" prop in the  reactivesearch ecommerce demo, it worked as expected, here is the [patch](https://github.com/yytsui/reactivesearch/commit/8c6c6ee4059375a469b49d2a639b5f1c839b4dd8).

**Comment by divyanshu013** [comment]
Resolved via #478
