### ISSUE TITLE
Enhancement: ReactiveComponent setSort

### ISSUE THREAD

**Issue by miukimiu** [appbaseio/reactivesearch#434]
**Issue Type:**
Enhancement

**Platform:**
ReactiveSearch for Web

**Description:**
I'm creating my custom components with the help of the `<ReactiveComponent />`. As you can see in the video in the screenshot section I've created two custom dropdowns. One that sets a **query that matches** a determined field and in the other dropdown I would like to **sort** a specific field. 

I tried to use the following code even though I now that is just intended to be used to set queries and not sorts:

```
this.props.setQuery({
    query: {
        match: {
           site_description: {
              query: this.state.orderBySite,
              type: "phrase"
           }
        }
     },
    sort: [{ "workbook_name.keyword": { order: this.state.orderByName } }]
});
```

Is there any way that I can set my custom sort? 

**Screenshots:**
https://www.useloom.com/share/37d66ec1834f4c47a3be92a269961279

**Reactivesearch version:** x.y.z
2.6.6

And once again that you for this amazing project! It's really making my work faster!

**Comment by siddharthlatest** [comment]
@miukimiu You could update the `setQuery` prop (e.g. with using state) when the value of options change in your custom sort dropdowns.

**Comment by miukimiu** [comment]
Hi,
I'm updating. Every time when the value of the options change for both select boxes the state is updated. 

But inside the ` this.props.setQuery` only the `query` object works. The `sort` object doesn't work.

```
state = {
    orderBySite: "IPH",
    orderByName: "asc"
  };

  setOrderBySiteValue = value => {
    this.setState({ orderBySite: value });
  };

  setOrderByNameValue = value => {
    this.setState({ orderByName: value });
  };

componentDidUpdate(prevProps, prevState) {
    if (
      this.state.orderBySite !== prevState.orderBySite ||
      this.state.orderByName !== prevState.orderByName
    ) {
      this.props.setQuery({
        query: {
          match: {
            site_description: {
              query: this.state.orderBySite,
              type: "phrase"
            }
          }
        },
        sort: [{ "workbook_name.keyword": { order: this.state.orderByName } }]
      });
    }
  } 
```

**Comment by metagrover** [comment]
Hi @miukimiu this is an expected behavior. Fundamentally, `sort` query gets applied to the source component, it doesn't get leaked on to the component's subscribers for the obvious reasons (that we don't want one component's sort query leaking into other component's sort query).

For your case here, you'd need to apply the sort query to the source component's `defaultQuery` - as in, whenever there is a change in the sort dropdown, you should update your result component's `defaultQuery`. We internally watch for the changes on the `defaultQuery`, so that will be reflected instantly.

Hope this helps.

----

@divyanshu013 we should clarify the usage of sort query w.r.t. to `defaultQuery` and `customQuery` in the docs properly.

**Comment by Arvind6353** [comment]
Hi , AM trying the default query as below : 
```  defaultQuery={(value, props) => ({
                "sort" : {
                  "date_original": {"order": "desc"}
                }
              })}``` . 

Am getting 400 bad request from server [{"type":"parsing_exception","reason":"no [query] registered for [sort]"

Note : am also using custom query .

**Comment by metagrover** [comment]
Hi @Arvind6353, can you share a codesandbox replicating this issue?
