### ISSUE TITLE
How to find out if there is 0 result

### ISSUE THREAD

**Issue by shili167** [appbaseio/reactivesearch#469]
Hi, 

I would like to setState in App.js if there is No Results/0 results returning from search. Is there a way to do that?

Thanks!

**Comment by metagrover** [comment]
You can use `onResultStats` prop for the same, but then it's currently tricky to use that - since it can lead to an infinite loop of re-rendering because of its buggy implementation.

We have already resolved this behavior - there is a [pending PR](https://github.com/appbaseio/reactivesearch/pull/461) which fixes this issue, but it will be a breaking change and we will soon release it in `v3.0.0`.

For now, in order to prevent the infinite loop you can use the following solution:

```js
onResultStats={(total, took) => {
	if (this.oldTotal === total) {
		// this prevents an unnecessary update of state ~ hence, no re-rendering
		return 'found ' + total + ' results in ' + took + 'ms.';
	} else {
		this.oldTotal = total;
		this.setState({
			// update your state here
		});
		return 'found ' + total + ' results in ' + took + 'ms.';
	}
}}
```

Hope this helps!

**Comment by shili167** [comment]
Thank you!
