### ISSUE TITLE
Reactivesearch support ResultTable 

### ISSUE THREAD

**Issue by tatdatpham** [appbaseio/reactivesearch#608]
How to create result as table with Reactivesearch ? Thank!

**Comment by siddharthlatest** [comment]
@tatdatpham This is a better question for StackOverflow. You can do this by using `ReactiveList` which allows custom rendering of data, and use a Table component like react-table in the `onAllData` prop.

**Comment by tristanreid** [comment]
It would be nice to have a ResultTable for large queries, to automatically handle pagination.

**Comment by siddharthlatest** [comment]
@tristanreid Since there are already very feature-rich table components out there, we made a conscious decision to not support one as part of the library.

We have created an [app](https://youthful-shockley-cfbba8.netlify.com/) that shows this using React virtualized list that can be purchased [here]( https://www.reactiveapps.io/datagrid-app).

**Comment by rgb-panda** [comment]
@siddharthlatest Hello, the purchase app link for table view is broken, is it no longer available?

**Comment by bietkul** [comment]
@karabi Updated the link
