### ISSUE TITLE
Question: Possible to show nothing (not "no results") when not searching?

### ISSUE THREAD

**Issue by carlopascual** [appbaseio/reactivesearch#631]
As the title says, is it possible to show nothing on the results when you haven't typed anything in a DataSearch field? I'm having flashes of the results of `match_all` or `match_none` when I search.

**Comment by siddharthlatest** [comment]
Hey @carlopascual, you should be able to use the `defaultQuery` prop in your Result component to match_none by default. Whenever the user is typing something in the search box, you can use its `onValue` listener to remove the defaultQuery condition.

Hope this helps.

**Comment by carlopascual** [comment]
Hi @siddharthlatest, thanks for the input! I tried it out though, and it still briefly shows. I made a sandbox using the example for DataSearch to show you how it looks like. Try putting a value in the DataSearch component repeatedly to see a flash of the no results component. 

https://codesandbox.io/s/xppv7q47yo

**Comment by metagrover** [comment]
Does this work for you - https://codesandbox.io/s/nnm79llpr4?

I removed the customQuery from the DataSearch component because it's unnecessary. It seems to be working for me - not sure why though 😅 

Anyway, if this still persists, we can keep this issue open and I can look into the rendering logic for the result component.

**Comment by carlopascual** [comment]
Hi @metagrover, in your example, if you look closely, it renders a "match_all" before the actual result.. It's not that big of a deal when you have a lot of results, but when you're expecting only one or two hits, it shows all the content before the actual filtered results.

Here's a screen grab of it:
https://streamable.com/xogs8

**Comment by gaving** [comment]
Hi - I don't suppose this issue got tackled anywhere else?

We've back button functionality within our app and when we page back to the results we've a bunch of different queries firing before the filters are applied, resulting in this flash of results before the proper filtered ones appear.

This would be a minor issue normally - but we've a requirement to audit everything that leaves the server so we're potentially saying a user has seen results they haven't!

**Comment by siddharthlatest** [comment]
@gaving Which version of ReactiveSearch are you seeing this happening on? With v3.x, the above issue has been solved. We have seen users with your situation (a combination of controlled filters + search) where only one query is fired instead of multiple, i.e. it works as expected.

Here's the above code sandbox where this issue was reported on, but it doesn't occur with the latest release: https://codesandbox.io/s/datasearch-fv4d9.

**Comment by gaving** [comment]
Hi @siddharthlatest -

Interesting. We're on 3.0.0-rc.22... I'll try rc23 and see if it sorts it. I'll compare what you have in the sandbox as I can see it works there.

Only difference I can see at a glance is our `react` prop is an array i.e.

```
  react={{
    and: [
      'q',
      'BasicSearch',
      'TownFilter',
      'AgeFilter',
      'GenderFilter',
    ],
  }}
```

**Comment by gaving** [comment]
Hi @siddharthlatest -

Same effect with RC23. Admittedly a bit confusing since our app has more filters going on, and our `history.back()` button is really using URL parameters to refresh the search results.

However I managed to create a bit of weirdness with your https://fv4d9.csb.app/ example, if you go to page 2 on launch and then do a single letter search, you'll get 2 requests with the first being a spurious `match_all` request, i.e.:-

```
{"preference":"SearchResult"}
{"query":{"match_all":{}},"size":10,"_source":{"includes":["*"],"excludes":[]},"from":0}
```
