### ISSUE TITLE
Using JSX for ToggleButton labels causing URLParams to return null

### ISSUE THREAD

**Issue by ghost** [appbaseio/reactivesearch#827]
**Issue Type:**
Bug

**Platform:**
Web

**Description:**
If you use JSX components from the labels in ToggleButtons it breaks the URL parameter
`?ShapeToggle=[null,null,null]`
**Screenshots:**

**Minimal reproduction of the problem with instructions:**
https://codesandbox.io/s/4wp8mm20k7

**Reactivesearch version:** 
2.16.1

**Comment by jyash97** [comment]
Hey @george-dotdev 

This is expected behavior since we don't support JSX in `label`, we can only pass `string` to the label. Read more [here](https://opensource.appbase.io/reactive-manual/base-components/togglebutton.html#props).

 If you want custom control, you can create a [custom component](https://opensource.appbase.io/reactive-manual/advanced/reactivecomponent.html).

**Comment by ghost** [comment]
@metagrover @jyash97 If i made a PR for this would it be accepted?
I was thinking that it could change to use the value of the current values instead of the title.
