### ISSUE TITLE
Passing tags/keywords to SelectedFilters while using them as tags in ReactiveList

### ISSUE THREAD

**Issue by Danelicious** [appbaseio/reactivesearch#832]
**Issue Type:**
Not sure if bug or a migration issue. 

**Platform & Version:**
ReactiveSearch Web 3.0.0-beta-3

**Description:**

I am trying to replicate[ GitXplore](https://codesandbox.io/s/github/appbaseio-apps/gitxplore-app/tree/master/). Everything works as expected, except for the tags/topics in ReactiveList. Usually you can click on a topic/tag and the chosen tag will be passed to the SelectedFilters and the results will be updated. It's also possible to unselect them, either by clicking on the tag or by removing it from the filter on the left side. With all dependcies updated to the latest version, it won't work anymore. See a Codesandbox example [here](https://codesandbox.io/s/wyzw4qx6r7). Any idea what need to be fixed in order to make the tag/topic filter work again? I described my problem also at StackoverFlow [here](https://stackoverflow.com/questions/54704827/passing-items-keywords-to-selectedfilters-while-using-them-as-tags-in-reactiveli)  , but it seems that other issues in the past didn't get much attention over there, so I am trying my luck here. Thanks in advance.

**Comment by metagrover** [comment]
This is due to the changes in controlled and uncontrolled components introduced in v3. Instead of `defaultSelected` (as per v2) or `defaultValue` (as per v3), you will have to use `value` props (i.e. controlled behavior) for the component to enable this.

Read more about controlled components [here](https://reactjs.org/docs/forms.html#controlled-components) and in [our migration guide as well](https://opensource.appbase.io/reactive-manual/v3/advanced/migrationguide.html#controlled-and-uncontrolled-component-behaviors).

**Comment by Danelicious** [comment]
Thank you for the clarification. It works now!
